<?php
$allLanguages = array(
    "Afrikaans",
    "albanès",
    "Amharic",
    "àrab",
    "aragonès",
    "armeni",
    "asturià",
    "Azerbaidjan",
    "Basc",
    "bielorús",
    "bengalí",
    "bosnià",
    "bretó",
    "búlgar",
    "català",
    "Kurd central",
    "xinès",
    "xinès (Hong Kong)",
    "Xinès (simplificat)",
    "Xinès (tradicional)",
    "cors",
    "croat",
    "txec",
    "danès",
    "holandès",
    "Anglès",
    "Anglès (Austràlia)",
    "Anglès (Canadà)",
    "Anglès (Índia)",
    "Anglès (Nova Zelanda)",
    "Anglès (Sud-àfrica)",
    "Anglès (Regne Unit)",
    "Anglès (Estats Units)",
    "Esperanto",
    "Estonià",
    "ferroès",
    "filipí",
    "finès",
    "francès",
    "francès (Canadà)",
    "francès (França)",
    "francès (Suïssa)",
    "Gallec",
    "Geòrgia",
    "alemany",
    "Alemany (Àustria)",
    "Alemany (Alemanya)",
    "Alemany (Liechtenstein)",
    "Alemany (Suïssa)",
    "grec",
    "guaraní",
    "Gujarati",
    "Hausa",
    "Hawaià",
    "hebreu",
    "Hindi",
    "hongarès",
    "islandès",
    "indonès",
    "Interlingua",
    "irlandès",
    "italià",
    "Italià (Itàlia)",
    "Italià (Suïssa)",
    "japonès",
    "Kannada",
    "Kazakh",
    "Khmer",
    "coreà",
    "kurd",
    "kirguis",
    "Lao",
    "llatí",
    "letó",
    "Lingala",
    "lituà",
    "Macedoni",
    "Malai",
    "Malaiàlam",
    "maltès",
    "marathi",
    "Mongol",
    "Nepalí",
    "noruec",
    "Bokmål noruec",
    "Nynorsk noruec",
    "Occità",
    "Oriya",
    "Oromo",
    "Paixto",
    "persa",
    "polonès",
    "portuguès",
    "Portuguès (Brasil)",
    "Portuguès (Portugal)",
    "Punjabi",
    "Quechua",
    "Romanès",
    "Romanès (Moldavia)",
    "romanx",
    "rus",
    "gaèlic escocès",
    "serbi",
    "Serbo",
    "Shona",
    "Sindhi",
    "Cingalès",
    "Eslovac",
    "eslovè",
    "somalí",
    "Sotho meridional",
    "espanyol",
    "Espanyol (Argentina)",
    "Espanyol (Amèrica Llatina)",
    "Espanyol (Mèxic)",
    "Espanyol (Espanya)",
    "Espanyol (Estats Units)",
    "sundanès",
    "Swahili",
    "suec",
    "tajik",
    "tamil",
    "tàrtar",
    "Telugu",
    "Tailandès",
    "Tigrinya",
    "tongà",
    "Turc",
    "turkmans",
    "Twi",
    "Ucraïnès",
    "Urdu",
    "Uigur",
    "Uzbec",
    "vietnamita",
    "Való",
    "gal·lès",
    "frisó occidental",
    "Xhosa",
    "Yiddish",
    "Ioruba",
    "Zulu"
);
